/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOrgsOrgIdRouteImport } from './routes/_authenticated/orgs/$orgId'
import { Route as AuthenticatedOrgsOrgIdIndexRouteImport } from './routes/_authenticated/orgs/$orgId/index'
import { Route as AuthenticatedOrgsOrgIdMembersRouteImport } from './routes/_authenticated/orgs/$orgId/members'
import { Route as AuthenticatedOrgsOrgIdArticlesRouteImport } from './routes/_authenticated/orgs/$orgId/articles'
import { Route as AuthenticatedOrgsOrgIdArticlesIndexRouteImport } from './routes/_authenticated/orgs/$orgId/articles.index'
import { Route as AuthenticatedOrgsOrgIdArticlesArticleIdRouteImport } from './routes/_authenticated/orgs/$orgId/articles.$articleId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrgsOrgIdRoute = AuthenticatedOrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrgsOrgIdIndexRoute =
  AuthenticatedOrgsOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdMembersRoute =
  AuthenticatedOrgsOrgIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdArticlesRoute =
  AuthenticatedOrgsOrgIdArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdArticlesIndexRoute =
  AuthenticatedOrgsOrgIdArticlesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgsOrgIdArticlesRoute,
  } as any)
const AuthenticatedOrgsOrgIdArticlesArticleIdRoute =
  AuthenticatedOrgsOrgIdArticlesArticleIdRouteImport.update({
    id: '/$articleId',
    path: '/$articleId',
    getParentRoute: () => AuthenticatedOrgsOrgIdArticlesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orgs/$orgId': typeof AuthenticatedOrgsOrgIdRouteWithChildren
  '/orgs/$orgId/articles': typeof AuthenticatedOrgsOrgIdArticlesRouteWithChildren
  '/orgs/$orgId/members': typeof AuthenticatedOrgsOrgIdMembersRoute
  '/orgs/$orgId/': typeof AuthenticatedOrgsOrgIdIndexRoute
  '/orgs/$orgId/articles/$articleId': typeof AuthenticatedOrgsOrgIdArticlesArticleIdRoute
  '/orgs/$orgId/articles/': typeof AuthenticatedOrgsOrgIdArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orgs/$orgId/members': typeof AuthenticatedOrgsOrgIdMembersRoute
  '/orgs/$orgId': typeof AuthenticatedOrgsOrgIdIndexRoute
  '/orgs/$orgId/articles/$articleId': typeof AuthenticatedOrgsOrgIdArticlesArticleIdRoute
  '/orgs/$orgId/articles': typeof AuthenticatedOrgsOrgIdArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/orgs/$orgId': typeof AuthenticatedOrgsOrgIdRouteWithChildren
  '/_authenticated/orgs/$orgId/articles': typeof AuthenticatedOrgsOrgIdArticlesRouteWithChildren
  '/_authenticated/orgs/$orgId/members': typeof AuthenticatedOrgsOrgIdMembersRoute
  '/_authenticated/orgs/$orgId/': typeof AuthenticatedOrgsOrgIdIndexRoute
  '/_authenticated/orgs/$orgId/articles/$articleId': typeof AuthenticatedOrgsOrgIdArticlesArticleIdRoute
  '/_authenticated/orgs/$orgId/articles/': typeof AuthenticatedOrgsOrgIdArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/orgs/$orgId'
    | '/orgs/$orgId/articles'
    | '/orgs/$orgId/members'
    | '/orgs/$orgId/'
    | '/orgs/$orgId/articles/$articleId'
    | '/orgs/$orgId/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/orgs/$orgId/members'
    | '/orgs/$orgId'
    | '/orgs/$orgId/articles/$articleId'
    | '/orgs/$orgId/articles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/orgs/$orgId'
    | '/_authenticated/orgs/$orgId/articles'
    | '/_authenticated/orgs/$orgId/members'
    | '/_authenticated/orgs/$orgId/'
    | '/_authenticated/orgs/$orgId/articles/$articleId'
    | '/_authenticated/orgs/$orgId/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$orgId': {
      id: '/_authenticated/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$orgId/': {
      id: '/_authenticated/orgs/$orgId/'
      path: '/'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/members': {
      id: '/_authenticated/orgs/$orgId/members'
      path: '/members'
      fullPath: '/orgs/$orgId/members'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdMembersRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/articles': {
      id: '/_authenticated/orgs/$orgId/articles'
      path: '/articles'
      fullPath: '/orgs/$orgId/articles'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdArticlesRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/articles/': {
      id: '/_authenticated/orgs/$orgId/articles/'
      path: '/'
      fullPath: '/orgs/$orgId/articles/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdArticlesRoute
    }
    '/_authenticated/orgs/$orgId/articles/$articleId': {
      id: '/_authenticated/orgs/$orgId/articles/$articleId'
      path: '/$articleId'
      fullPath: '/orgs/$orgId/articles/$articleId'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdArticlesArticleIdRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdArticlesRoute
    }
  }
}

interface AuthenticatedOrgsOrgIdArticlesRouteChildren {
  AuthenticatedOrgsOrgIdArticlesArticleIdRoute: typeof AuthenticatedOrgsOrgIdArticlesArticleIdRoute
  AuthenticatedOrgsOrgIdArticlesIndexRoute: typeof AuthenticatedOrgsOrgIdArticlesIndexRoute
}

const AuthenticatedOrgsOrgIdArticlesRouteChildren: AuthenticatedOrgsOrgIdArticlesRouteChildren =
  {
    AuthenticatedOrgsOrgIdArticlesArticleIdRoute:
      AuthenticatedOrgsOrgIdArticlesArticleIdRoute,
    AuthenticatedOrgsOrgIdArticlesIndexRoute:
      AuthenticatedOrgsOrgIdArticlesIndexRoute,
  }

const AuthenticatedOrgsOrgIdArticlesRouteWithChildren =
  AuthenticatedOrgsOrgIdArticlesRoute._addFileChildren(
    AuthenticatedOrgsOrgIdArticlesRouteChildren,
  )

interface AuthenticatedOrgsOrgIdRouteChildren {
  AuthenticatedOrgsOrgIdArticlesRoute: typeof AuthenticatedOrgsOrgIdArticlesRouteWithChildren
  AuthenticatedOrgsOrgIdMembersRoute: typeof AuthenticatedOrgsOrgIdMembersRoute
  AuthenticatedOrgsOrgIdIndexRoute: typeof AuthenticatedOrgsOrgIdIndexRoute
}

const AuthenticatedOrgsOrgIdRouteChildren: AuthenticatedOrgsOrgIdRouteChildren =
  {
    AuthenticatedOrgsOrgIdArticlesRoute:
      AuthenticatedOrgsOrgIdArticlesRouteWithChildren,
    AuthenticatedOrgsOrgIdMembersRoute: AuthenticatedOrgsOrgIdMembersRoute,
    AuthenticatedOrgsOrgIdIndexRoute: AuthenticatedOrgsOrgIdIndexRoute,
  }

const AuthenticatedOrgsOrgIdRouteWithChildren =
  AuthenticatedOrgsOrgIdRoute._addFileChildren(
    AuthenticatedOrgsOrgIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrgsOrgIdRoute: typeof AuthenticatedOrgsOrgIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrgsOrgIdRoute: AuthenticatedOrgsOrgIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
